broker-host: localhost
broker-port: 1883
mapping-type: topic-pair
publish-topic: cs/josev
subscribe-topic: josev/cs
to-mqtt:
  timeout-ms: 10000
  request-template:
    id: ${id}
    name: ${verb}
    type: request
    data: ${data}
  response-filter:
    filter:
      path: .type
      value: response
    data-path: .data

