broker-host: localhost
broker-port: 1883
mapping-type: topic-pair
publish-topic: cs/josev
subscribe-topic: josev/cs
to-mqtt:
  timeout-ms: 10000
  request-template:
    id: ${uuid()}
    name: ${verb}
    type: request
    data: ${data}
  response-filter:
    filter:
      path: .type
      value: response
    data-path: .data

from-mqtt:
  # the AFB API to call
  api: josev
  request-extraction:
    verb-path: .name
    data-path: .data
    filter:
      path: .type
      value: request
  response-template:
    id: ${request.id}
    name: ${verb}
    type: response
    data: ${data}

  # this will call a verb, but won't generate a response
  event-extraction:
    verb-path: .name
    data-path: .data
    filter:
      path: .type
      value: update

